jobs:
  name: Win
  runs-on: "windows-latest"
  steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        python-version: 3.8
        channels: conda-forge
        channel-priority: true
    - shell: bash -l {0}
      run: |
        conda create --name TEST python=3.8 --file requirements.txt --file test_requirements.txt
        conda info
        conda list
        printenv | sort
    - shell: bash -l {0}
      run: |
        python -m pip install . --no-deps -vv
        pytest -s -rxs -v -k "not integration" compliance_checker
